//
//  ViewControllerLynbrook.swift
//  
//
//  Created by Mahit  Tanikella on 5/24/20.
//

import UIKit

class ViewControllerLynbrook: UIViewController {
    
    @IBOutlet weak var interestField: UITextField!
    @IBOutlet weak var textView: UITextView!
    
    var lynbrookClubs:[Club] = [
        Club(name:"Zectangle Club", email: "N.Ngyuen", description: "No Description."),
        Club(name:"YAK", email: "Taylor", description: "YAK is a community service club that focuses on interacting and socializing with children. What makes YAK unique is the level of engagement with kids at our events. We offer a variety of events, such as exchanging pen pal letters with students at Dilworth Elementary, babysitting children at John Muir Elementary, and reading books to kids at various libraries. Come out and experience it for yourself!"),
        Club(name:"Women in STEM", email: "Welsh", description: "Lynbrook's Women in Science, Technology, Engineering and Mathematics (WiSTEM) club provides a forum for women to present their science ideas. We strive to encourage and promote aspiring female scientists, engineers, and mathematicians through tech companies, labs, museum outings, speaker presentations, and more! The club offers science experiments and presentations during the weekly meetings. Volunteer opportunities are available through teaching children science at Calabazas library, and the club offers tech tours and guest speakers. The Bay Area Research Exposition is a wonderful stepping stone to creating their own research proposals."),
        Club(name:"Web Development Club", email: "Levin", description: "We're a community for members to explore web technologies. Our weekly meetings discuss computer networking and the Internet as well as current advances in frontend and backend web development. We hold workshops on how to code your very own websites and web apps, whether you're just starting out or already a code ninja. Through our lessons and hands-on projects, you'll be able to build a nice-looking personal website (frontend) or even a server for your interactive blog (backend). Also, you’ll discover the exciting features hidden in ordinary browsers and experience the technical wonders of the web!"),
        Club(name:"Virtuosity", email: "Levin", description: "No Description."),
        Club(name:"Viking Vocalists (Previous Name: Capriccio A Cappella)", email: "Isola", description: "Have you ever wanted to sing with Pentatonix or join the Bellas? Want to perform outside the shower? This is your chance: Capriccio A Cappella is the vocal music club at Lynbrook. As part of our club, we perform music with special choreography at our biannual concerts. During club meetings, we play musical games including riff-offs and harmony challenges, rehearse for our upcoming performances, and, most importantly, make lifelong friendships. If you have an interest in singing, dancing, playing the piano, or beatboxing, you should join. We’re open to all interested whether you have musical background or not! Everyone’s welcome!"),
        Club(name:"Viking Buddies", email: "Garcia, Herz", description: "We are an on-campus service club dedicated to fostering friendships with the special education students at our school. We are non-judgmental, warm community that appreciates everyone for their own abilities and skills. Viking Buddies offers direct volunteering opportunities for everyone on campus."),
        Club(name:"Vertigo Literary Magazine", email: "Willson", description: "Vertigo is the official literary magazine of Lynbrook High School. Established in 1995, the magazine continues to encourage widespread appreciation for and interest in creative writing and art. At the beginning of each school year, the edit board reviews student applications to select its inspired staff. Vertigo releases three issues throughout the year: two web issues and an annual print issue, which is distributed for free and tangibly presents the efforts of talented Lynbrook writers and artists for the rest of the community to enjoy."),
        Club(name:"Ted-Ed", email: "N.Ngyuen", description: "No Description."),
        Club(name:"Team HBV", email: "Kidane, Kraemer", description: "Lynbrook Team HBV is an interest club dedicated to raising awareness about Hepatitis B and other easily preventable diseases that disproportionately affect people of Asian descent by working with the Asian Liver Center at Stanford University. As a high school chapter of Team HBV, the goal of our club is to cultivate and expand upon our members’ interests in pre-medicine, public health, and leadership skills through volunteer and internship opportunities, leadership workshops, and oral presentations. Members will have access to inter-chapter events, such as conferences and volunteer events, on top of Stanford guest speaker events at Lynbrook."),
        Club(name:"Surgery Interest Club", email: "N.Ngyuen", description: "Surgery Interest Club focuses on providing members with a substantial amount of knowledge about surgery. Topics include, but are not limited to: anatomy, the job of a surgeon, and new technological advancements constantly arising within the surgical field. Past events have included guest speakers and workshops for activities, such as suturing.This club will provide learning experiences for students who have even the slightest interest in surgery. Please feel free to join!"),
        Club(name:"Students for Literacy", email: "Ashworth", description: "Lynbrook’s Students For Literacy (SFL) club aims to promote the love of reading within the Lynbrook school community by organizing interesting club meetings (i.e. book discussions, poetry readings, and creative writing) and book matching events in which students receive a book based on their responses to an interest survey. The club also spreads the importance of reading outside the school community through volunteer reading sessions and writing workshops. The goal of this club is to encourage people with any socioeconomic status to empower themselves through reading."),
        Club(name:"Student Health Outreach for Kids", email: "Ene", description: "SHOK is designed to educate children about leading healthy lifestyles. But our main target students are those who come from low-income families. Our main goal is to educate the children about eating right and do so by conducting interactive workshops. The interactive workshops consist of hands-on learning activities, skits, and outdoor activities. We strive to teach students to make the right choices for hot lunch, like choosing the salad option instead of tater tots. Our goal is to reach out to as many of the students from low-income families as we can in order to ensure them a healthy future."),
        Club(name:"Speech & Debate", email: "Welsh", description: "Speech and Debate is one of the largest student organizations at Lynbrook High School. We are a professionally coached academic team that gives students unmatched opportunities to hone their formal public speaking technique, critical analysis ability, and research skills. We compete at all levels of tournaments, from local Bay Area tournaments to national level tournaments. In addition, we offer students exposure to advanced topics in philosophy, politics, science, and business. Come join our award-winning team and learn how you can get in on the action!"),
        Club(name:"Spanish Club", email: "Revilla", description: "Spanish Club is a place for which students can enrich their knowledge of the Hispanic culture. This club is not only for Hispanic students or students taking a Spanish class, but for anyone who would like to enhance their cultural awareness. We have bi-monthly presentations about food, culture, and sports which are popular in Spanish-speaking countries."),
        Club(name:"Smash Bros Club", email: "N.Ngyuen", description: "No Description."),
        Club(name:"Science Olympiad", email: "Leung", description: "Science club provides two major resources/activities: (1) information and resources relating to all science-related competitions and (2) hands on science demonstrations. This club is also the major organizer of the Lynbrook STEM day event, an annual school-wide collaboration between all STEM-related clubs that involves guest speakers, club booths, and a science competition."),
        Club(name:"Science Club", email: "milespereira@yahoo.com", description: "We hope to incorporate hands on learning to improve students awareness of medicine"),
       Club(name: "Agape", email: "Dunlap", description: "Agape Christian Club is a place for Christians to create a loving community on campus. We also strive to spread God's love across of campus with many activities throughout the year. We do worship, pray, games, and other activities. On occassion, we have a speaker come and speak a message to students. Praise nights with other schools in our district are also organized throughout the year. We welcome both Christians and non Christians to our club!"),
        Club(name: "AISA", email: "Ellington", description: "Our club aims to promote South Asian culture in the Lynbrook community. Members explore and celebrate different customs through several games and activities. Each year, we host Silsilay, Lynbrook's Indian cultural showcase that involves schools from all around the Bay Area. All proceeds are donated to charity to promote the sustainable development and growth of rural Indian communities."),
        Club(name: "American Cancer Society", email: "Isola", description: "We, Lynbrook ACS, are an outreach arm for American Cancer Society. During the course of the school year, we will learn about different types of cancer and how they can be prevented through member-involved activities. In addition, we will provide numerous volunteer activities for members to participate in, such as working at the American Cancer Society Discovery Shop. One of the biggest fundraising events of American Cancer Society is Relay For Life, which is held on many local campuses throughout the school year. Together, Lynbrook ACS hopes to provide you with both knowledge and fun as we strive for a cancer-free world."),
        Club(name: "Animal Services and Protection", email: "M. Reynolds", description: "Animal Services and Protection (ASAP) is dedicated to advocating for animal welfare. We are associated with a variety of organizations that allow members to volunteer both in person and online with many different kinds of animals. We also encourage members to present on topics including endangered species, environmental studies, and animal abandonment/abuse."),
        Club(name: "Anime Club", email: "T. Nguyen", description: "Anime club is a club for anyone who is interested in anime or Japanese culture. Members will be exposed to all genres and periods of anime. Typical meetings include showing an episode of an anime series."),
        Club(name: "ARK", email: "Quindipan", description: "We high school students face stress, drama and negativity from time to time. The Acts of Random Kindness Club strives to make high school a little more pleasant by conducting uplifting campaigns, activities, and projects (called ARKtivities), because it’s the little things in life that make a difference."),
        Club(name: "ArtReach", email: "M. Reynolds", description: "Artreach is a club that aims to serve and help the community through arts and crafts. Members create arts and crafts that will be donated to different organizations in the community. Occasionally, members also create take-home projects for themselves. Members will also be introduced to various volunteering opportunities related to arts and crafts, such as an arts and crafts activity with senior citizens."),
        Club(name: "Astrophysics Club", email: "T. Nguyen", description: "This organization will promote interest in the field of astrophysics. We will hold weekly meetings to discuss and present on various topics related to Astrophysics. We will host star parties in the winter months, taking advantage of the early sunset time during the winter. We will host guest speaker meetings in which members can learn what it is like to be an aeronautical engineer and astrophysicist."),
        Club(name: "Athletics Unlimited", email: "Bale", description: "No Description"),
        Club(name: "Breakdance", email: "Martell", description: "Breakdance club is a place for students to learn and improve their dancing skills. We require no previous experience, as long as new members are willing to learn. Our club has created a community of culture and passion focused on the creative aspect of dance, and we urge each student to develop their own style. Through hard work and dedication, we each practice and perfect our style in order to perform at events such as rallies. During club meetings, our goal is to help and motivate students to improve."),
        Club(name: "CardioMed Club", email: "Chan", description: "CardioMed is a high school organization dedicated to the science of cardiology, the practice of cardiothoracic surgery, and inspiring our members to pursue these fields as their interests. By involving our members in active discussions, unique activities, and club events, we hope to create an environment in which every member feels compelled to actively contribute, and have an experience unique among the sea of interest clubs."),
        Club(name: "Character Design Club", email: "M. Reynolds", description: "Character Design Club is focused on fostering a passion for art and providing a learning environment for students of all skill levels with an interest in drawing and creating characters. We create opportunities for members to share their art both within and outside the Lynbrook. Through activities such as art exchanges, prompt based contests, figure drawing sessions, and games such as pictionary, we hope to create an engaging art community."),
        Club(name: "Computer Science Club", email: "Fulk", description: "Computer Science club is focused on exploring all subfields of computer science, learning about various algorithms and preparing for competitions such as USACO. We also spend time understanding what artificial intelligence is, and present our research to one another through weekly presentations. Topics are understandable to all members, regardless of their computer science background, so all are welcome to come!"),
        Club(name: "Conservation Action Association (CAA)", email: "McCown", description: "We're CAA (Conservation Action Association), decidedly the coolest environmental club on Lynbrook campus. Our purpose is to spread awareness about the environment/its protection through weekly events/activities, trivia, scholarship challenges, special guests, and more. If you're passionate in helping to protect the Earth or interested in gaining many volunteering hours, ranging from park cleanups to animal shelter events, trivia prizes, internship opportunities, socials, and meeting new people, come join us!"),
        Club(name: "Cooking Arts Club", email: "M. Miller", description: "The LHS Cooking Arts club is a culinary interest club open to anyone who wants to learn. As a club, we will guide Lynbrook students by teaching them the standard basics and unveiling the exciting and engaging work that goes on inside the kitchen. Throughout the course of this year, members will undergo a series of lectures, demos, workshops, and events that will exercise their ability to lead with decisiveness, to be proactive, and to remain composed during tough situations."),
        Club(name: "CSF", email: "Signore", description: "California Scholarship Federation, or CSF, is a highly coveted honor society that provides members with several opportunities to perform community service while pursuing academic excellence. Our volunteer events include helping out at marathons, festivals, RAFT, Sacred Heart, West San Jose Opera, Operation Care and Comfort, and much more!"),
        Club(name: "DECA", email: "Fulk", description: "DECA is an internationally recognized competitive business club that aims to create opportunities that enhance business knowledge and foster the entrepreneurial spirit amongst high school students. Competitive events span across five career clusters: business management, marketing, finance, hospitality/tourism, and entrepreneurship. Lynbrook DECA members get the chance to compete in events in these clusters at the regional, state, and international level."),
        Club(name: "Economics Club", email: "Signore", description: "Economics Club is a competition/interest club that hopes to offer Lynbrook Students with the unique opportunity to pursue pathways in the field of economics and finance. We offer unique international and prestigious competitions like the National Economics Challenge, Stanford Precollegiate Economics Challenge, KWHS Investment Challenge and many more!"),
        Club(name: "Engineering Club", email: "Frazita", description: "Lynbrook Engineering Club exposes members to different topics under the vast field of engineering, such as computer, electrical, biomedical, mechanical, and civil engineering. During meetings, members participate in hands-on STEM activities and demos, learning about specific subjects within the engineering world. We also participate in a variety of national competitions, including our main competition, Technology Student Association's TEAMS."),
        Club(name: "FBLA", email: "Robledo", description: "Here at Lynbrook FBLA, we are devoted to helping prepare young adults to become emerging leaders and entrepreneurs of tomorrow. FBLA is a club with something for everyone -- we offer a wide variety of competitive events at the local, state, and national levels. Along with competing, members will have the opportunity to attend overnight conferences in cities across the nation. Lynbrook FBLA also provides members the chance to participate in community service projects, fun socials, high-profile guest speaker events, business partnership projects, and exclusive business tours."),
        Club(name: "Film Club", email: "M. Reynolds", description: "Film club aims to created an environment in where students can explore the art and process of film making. District wide film festivals offer students opportunities for hands on filmmaking. The club leaders’ job is to facilitate as well as inspire students to create. Tutorials will be scheduled upon request. Film/video critiques will be a core component of Film Club"),
        Club(name: "Forensic Science Club", email: "Goldstein", description: "Forensics Science Club is focused providing a fun experience to students while learning about Forensics science. By incorporating different aspects of forensics, such as TV shows and different fields in Forensics, we hope that students can learn more about Forensics and have fun at the same time. We encourage students who have interest in Forensics science to learn beyond TV shows, and to dive into real activities that Forensic Scientists do."),
        Club(name: "French Club", email: "Louie", description: "French Club provides the opportunity to learn and spread awareness about the French culture in many ways through interactive games, videos, and other activities. Member meetings consist of trivia questions, scavenger hunts, cheese tastings, crêpe parties, and some games of pétanque! French Club also hosts annual school-wide activities, such as the Bûche de Noël contest in December, National French Week in March, and Pétanque in April. All students are welcome, whether or not they take a French language course."),
        Club(name: "French Honor Society", email: "Schang", description: "French Honor Society is dedicated to encouraging and advancing the study of the French language and culture beyond the classroom! In addition to holding meetings every other week, we run weekly salons where we play fun games to improve our French vocabulary and speaking skills, as well as snack on French food. French Honor Society members also tutor other French students regularly and organize a variety of events throughout the year, including an interschool debate and a schoolwide Mardi Gras celebration. All of our meetings and activities are held in French for the full immersion experience."),
        Club(name: "Gender and Sexuality Alliance", email: "J. Lu, Ashworth", description: "Meeting every Thursday lunch, GSA is a chill social/support club for those who identify or are allied with the LGBTQ+ community. It's a safe space; anyone and everyone is welcome! Through the year we'll explore LGBTQ+ topics and issues through presentations, discussions, activities, and gayme days! We strive to help educate people and create an accepting environment Lynbrook."),
        Club(name: "HEAL (Health Education Association of Lynbrook)", email: "N. Nguyen", description: "HEAL is a club that teaches members about professions in the medical field outside of the popular options: doctors or nurses. Instead of teaching students about medicine itself, HEAL makes use of guest speakers and club events in order to showcase the numerous possibilities in the medical field. For example, if a student is interested in neuroscience we encourage that student look past becoming a neuroscientist and consider a career such as clinical psychology."),
        Club(name: "Indesign", email: "Kruk", description: "Calling all who love fashion!! If you have ever wanted to model and walk down a runway, or design your own clothing pieces, join InDesign! At the end of the school year, InDesign holds a fashion show where co-ed models and designers alike have the opportunity to walk down the runway and showcase their sewn pieces. No prior experience is necessary! Through our workshops and socials, we will teach you everything you need to know! This is an amazing opportunity for you to meet new people and try something different! Everyone is welcome!!"),
        Club(name: "Interact", email: "Agarwal", description: "Interact is an international organization of service and social clubs for young people of secondary school age that fosters leadership and responsible citizenship and promotes international understanding and peace. Each year, Interact clubs complete at least one community service project and at least one project that furthers international understanding and goodwill. Previous projects have been involved in issues such as homelessness, education, and mental health. Interact's five primary avenues of service include the following: community, international, school, environmental, and fundraising. Students of all grade levels have will have opportunities to gain leadership experiences and be involved in service events."),
        Club(name: "International Club", email: "Miller", description: "Strives to bring students together with opportunities for cultural exchange and a chance to learn more about the world. We create a welcoming home for students from all over the world with all sort of different backgrounds. In addition, we provide help for English learning students."),
        Club(name: "International Thespian’s Society", email: "Howard", description: "Thespian Society meets every Monday during lunch in Studio 74. Our goal is to teach our members about all aspects of theater through workshops and watching shows! We are an international club meaning that we belong to a society worldwide. Please drop by and check us out!"),
        Club(name: "Intersections: A Social Justice Club", email: "Pallone", description: "We want to create waves. From challenging mental health stigma to understanding anti-blackness in Asian communities, we hope to find new perspectives and fight, in solidarity, against oppression. As a social justice club, our main avenues of work include projects, events, and the backbone of our club: high-quality club meetings that present facts, pose questions, and raise awareness on social issues. Intersections' goal is to thoughtfully engage school administration and students in social issues, promote tolerance and solidarity, and foster activism."),
        Club(name: "Japanese Club", email: "Kitchen", description: "Japanese Club is an interest club focused on the exploration of Japanese culture and life through activities, presentations, and food. We have powerpoints every week, and interactive activities on occasion. Tons of fun, and no Japanese experience is required!"),
        Club(name: "Japanese National Honor Society", email: "Kitchen", description: "JNHS provides a place for people interested in Japanese culture and language to meet like-minded peers and promote the understanding of a foreign culture. We team up with the jnhs clubs from other schools to provide a fun environment for students to explore a foreign culture and practice the Japanese Language."),
        Club(name: "Junior State of America", email: "Martell", description: "The Junior State of America – or JSA in short – is a non-partisan civics club with a focus on political activities. Established in 1934, it is currently the largest national organization completely run by students. The club gathers weekly to discuss important national as well as international events affecting daily life and society. JSA is dedicated to developing leadership skills and increasing awareness in today’s political atmosphere in hope that members become better acquainted and more integrated within their communities."),
        Club(name: "Junior Taiwanese American Student Association (JTASA)", email: "Qin", description: "Lynbrook JTASA is a high school chapter under JTASA NorCal. The mission of JTASA is to share Taiwanese culture, history, and current events and to help empower young Taiwanese American citizens. Meetings are a combination of culture presentations as well as hands-on activities, and there are many after-school events with other JTASA chapters at schools like Cupertino, Irvington, and Mission San Jose. Additionally, JTASA hosts fun, social events like pearl milk tea making, which allows members to interact and network with people outside of the Lynbrook community. All ethnicities/identities are welcome."),
        Club(name: "Key Club", email: "Slaughter", description: "Key Club is the oldest and largest service organization for high school students whose goal is to encourage leadership through serving others. In addition to service projects, Key Club is affiliated with Kiwanis International and other upper service organizations for division, region, district, and international events. Some of the most notable large events include Fall Rally North at Six Flags and District Convention. Being a club full of spirit and fun, Key Club fosters a supportive environment for networking, memory-building, and everlasting friendships within Key Clubbers from all over the nation."),
        Club(name: "Korean Club", email: "Richmond", description: "Korean club is a club where the students who are interested in Korean culture can share and learn about Korea. The club will have numerous activities that will be both fun and informative. There will be Kpop, Korean food and more!"),
        Club(name: "Machine Learning Club", email: "Kwong", description: "The Machine Learning (ML) Club's goal is to educate members about the expanding fields of ML, Big Data, and Artificial Intelligence. We teach members how to create ML models and implement established libraries and tools such as Microsoft Azure, Scikit-learn, Keras, and Tensorflow. Come join us if you want to experience the practical applications of ML and be part of the big data revolution!"),
        Club(name: "Martial Arts Club", email: "Seike", description: "What is Aikijutsu? Is it an instrument? Of course not! Aikijutsu is a Japanese martial art based on the fighting style of the ancient samurai. In Aikijutsu club, you will be taught how to roll, throw, and put enemies into submissions. Along with all these techniques, you will also learn how to properly punch, kick, block, as well as practice all these techniques in sparring. Prior experience is unnecessary, and all newcomers are welcome."),
        Club(name: "Math Honor Society", email: "Korsunsky", description: "Lynbrook Math Honor Society is a student-led organization that participates in a multitude of math competitions, whether regionally in the Bay Area or nationally in the USA. We promote competitive and recreational mathematics, both in school and outside of school, with a goal of promoting math beyond the high school curriculum through presentations and other activities on and off campus. We have one of the highest attendance rates in Lynbrook and are in charge of running all of the school math contests, including the AMCs, Mandlebrot, and CAML."),
        Club(name: "Me to We", email: "Morelos", description: "Lynbrook High School's Me to We Club focuses on local and global issues pertaining to the five pillars: water, food, health, education, and opportunity. Me to We is an international charity and educational partner, working both domestically and internationally to empower and enable youth to be the agents of change. Our goal is to raise $10,000 through executing fundraisers and awareness projects in order to build a school in Totoras, Ecuador."),
        Club(name: "Mobile Development Club", email: "N. Nguyen", description: "Lynbrook Mobile Development Club strives to teach mobile development and programming to students. Our goal is to have every student be able to create an application to publish on the app store, and compete in school wide competitions such as hacakthons. We plan to cover all the basics of creating a mobile application, from the language it's written in, to designing it and adding major functionaility. MDC plans to cover the two most popular languages of mobile development - swift (for iOS) and Java (for Android)."),
        Club(name: "Mock Trial", email: "Pugh", description: "Mock Trial is a student academic team providing opportunities to hone oral advocacy and critical analysis skills. Team members role-play attorneys, witnesses and court personnel in trying a case before judges and scoring attorneys. Months of preparation and analysis of rules of evidence, criminal justice, and trial procedure culminate in competitive tournaments. Lynbrook Mock Trial is the current 2-time Santa Clara County Champion and a holder of various county, state, and international awards. If you’re looking to join a tight-knit team, develop speaking and acting skills, analyze cases, and interact with the law community, consider auditioning."),
        Club(name: "Model United Nations", email: "McCown", description: "Model UN is a competition club that aims to encourage students to improve their research and public speaking skills in a simulation of the UN. Participation in the club and its activities allows students to develop important connections and valuable experience in developing as leaders and understanding the purpose of diplomacy in the real world."),
        Club(name: "Music for Community", email: "Pakaluk", description: "Music for Community is a fun enviorment for instrumentalists and vocalists to pursue their passion while creating an impact on their community. From performing at retirement homes, teaching younger students, and organizing benefit concerts, we strive to explore the endless possibilites of music!"),
        Club(name: "Musicians' Society", email: "Isola", description: "Lynbrook Musicians Society strives to further members’ passion for the piano and for music, helping them in their journeys to becoming better musicians. Activities include performance meetings and masterclasses, as well as games and presentations regarding musical knowledge and exploration. The club shall also strive to contribute to the community through such actions as donations to charitable organizations and performances at senior centers."),
        Club(name: "National Chinese Honor Society", email: "Qin", description: "National Chinese Honor Society holds weekly meetings immersing members in the Chinese culture, holding fun events along with the informative presentations. With inter-club socials, the ping-pong tournament, Chinese tutoring event, and more, NCHS welcomes all students to learn more about China. All students, regardless of ethnicity or second language, are welcome to apply."),
        Club(name: "National Spanish Honor Society", email: "Esquivel", description: "Spanish Honor Society promotes a warm environment in which students who are looking to further their education in Spanish language and culture may expand their knowledge through interacting with others who share the same passion."),
        Club(name: "Neuroscience Club", email: "Levin", description: "Lynbrook Neuroscience's mission is to educate and excite fellow peers about the vast field of neuroscience and its ties to nearly every aspect of everyday life. We do this through interactive activities and presentations, brain dissections, discussions of exciting research going on in the field, and also through participating in the Brain Bee, an international neuroscience competition. We also bring in guest speakers; Bay Area scientists, physicians, and educators who are dedicated to studying the brain and nervous system. Anyone who is interested is welcome to join!"),
        Club(name: "NHS", email: "Yang", description: "The National Honor Society is a voluntary organization that strives to create enthusiasm for scholarship, to stimulate a desire to render service, to promote leadership, and to develop character in high school students. All National Honor Society members are expected to maintain membership requirements of the National Honor Society, including GPA, and to take part in National Honor Society service projects. The organization is currently partnered with Lynbrook's STTAR Tutor program."),
        Club(name: "Octagon", email: "Baugh", description: "Lynbrook Octagon is a service club focused on alleivating a variety of societal issues. We offer a variety of weekly volunteering events and fundraisers where you can meet new people. If you want to promote positive change in your community while having fun, be sure to check us out!"),
        Club(name: "Paper Airplanes", email: "Howden", description: "Paper Airplanes is a global non-profit that provides professional development , mentoring and educatonal opportunities for refugees. Paper Airplanes club members have the opportunity to join the Youth Exchange Program, which pairs lynbrook students with high-school aged refugees from Syria for a cultural exchange and also english tutoring. Paper Airplanes also runs fundraisers, and awareness campaigns related to the refugee crisis."),
        Club(name: "Photography Club", email: "Iams", description: "Photography Club is an interest club aimed to educate and inform the student body regarding basic photographic principles in preparation of entering various competitive art contests (i.e. PTA Reflections, Los Gatos PGLGEF, club-held photo contests). Our weekly meetings include a lesson accompanied by a hands-on demonstration. We maintain a library of equipment for our members to borrow and use to prepare for competitions or work for personal projects/portfolios."),
        Club(name: "PreMed", email: "Romander", description: "Pre-med in a club geared on showing students interested in healthcare the different areas of medicine. We educate our members about the fields of biology and medicine through informative presentations, guest speaker events, and practical applications of medical knowledge. We hope that we can help all of our members to not only become more knowledgeable about medicine, but also develop a passion for it."),
        Club(name: "Public Art Club", email: "Hage", description: "Lynbrook Public Art Club’s purpose is to preserve beauty within our community and campus while providing a volunteer option for students. We beautify areas of the city and host events for the public. Our work will be displayed in various locations of cities, hospitals, parks, museums, and a variety of other recreational centers. Within our club, not only will students refine their soft skills involving problem solving, planning, communication, and creative thinking skills critical for life later on, students will also be able to gain insight on certain areas of city management."),
        Club(name: "Red Cross Club", email: "A. Reynolds", description: "The Lynbrook Red Cross blends volunteering, certifications, and fun socials for an all around awesome club! Members have the opportunity to volunteer at small and large events, such as senior center visits and even helping out at major Red Cross parades and exhibitions. In addition, members can connect with the chapter to participate in committees that teach skills like CPR. Finally, Lynbrook Red Cross is a great way to meet new people from Lynbrook and other schools in the area through not only volunteering, but chapter wide socials, including ice skating and movie nights."),
        Club(name: "Robotics", email: "Kwong", description: "Lynbrook Robotics, FIRST Team 846 provides motivated students with the opportunities to excel in science, technology and business. Founded in 2001, Lynbrook Robotics operates within Lynbrook High School, a public school located in San Jose, CA in the heart of Silicon Valley. Our team is a student run, extracurricular organization with over one hundred members and has been operating for twelve years. Through participating in the FIRST Robotics Competition, our robotics program introduces students to engineering and helps them develop the skills they need to manage a complex project involving many individuals with talents in software, electronics, mechanics, and art."),
    ]
    
    override func viewDidLoad() {
        super.viewDidLoad()
        interestField.delegate = self
        // Do any additional setup after loading the view.
    }

    @IBAction func enterTapped(_ sender: Any) {
        textView.text = ""
        var interest = interestField.text!
        var clubInterests: [Club] = []
        for club in lynbrookClubs{
           if(club.description.containsIgnoringCase(find: interest) || club.name.containsIgnoringCase(find: interest)){
               clubInterests.append(club)
           }
        }
       
        if (clubInterests.count == 0) {
           textView.text = "No Results Found"
        }
       
        else {
           clubInterests = clubInterests.sorted(by: {$0.name < $1.name})
           for club in clubInterests {
               textView.text += "Club: \(club.name)\nContact Info: \(club.email)\nDescription: \(club.description)\n\n"
           }
        }
       
        textView.isScrollEnabled = true
        textView.isUserInteractionEnabled = true
        textView.showsVerticalScrollIndicator = true
        textView.showsHorizontalScrollIndicator = true
        textView.translatesAutoresizingMaskIntoConstraints = false
     }
    
}
extension ViewControllerLynbrook : UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
}
