//
//  ViewControllerCupertino.swift
//  ClubHub
//
//  Created by Mahit  Tanikella on 5/25/20.
//  Copyright © 2020 Mahit  Tanikella. All rights reserved.
//

import UIKit

class ViewControllerCupertino: UIViewController {
    
    
    @IBOutlet weak var interestField: UITextField!
    @IBOutlet weak var textView: UITextView!
    var cupertinoClubs = [
    Club(name:"Webcomic Art Club Cupertino", email: "tinotabletop@gmail.com", description: "Are you interested in becoming a published author or Webtoon artist? Or maybe you just want to draw fanart/art and post on social media? This club is the perfect match for you! Here we allow members to polish their story plot, hone their writing skills, and develop the technical skills needed in order to create comics (and other media) as well as learn the art of advertising and marketing their material alongside other peers with the same goal. This club combines the world of art, the realms of story writing, and the kingdom advertising into a club that can be enjoyed by all."),
    Club(name:"Tino TableTop Games Club", email: "tinoexplore@gmail.com", description: "Regardless of any experience in playing board games, anyone is welcome to learn and play board games. Our club creates a stress-reducing environment in which anyone can join in with their friends and have fun in exploring board games. We will also be hosting inter-club tournaments for prizes."),
    Club(name:"Tino Science Magazine/Explore", email: "tinoexplore@gmail.com", description: "If you love writing and are interested in science, this is the perfect fit for you! Our science magazine club offers a chance for students to learn and share their knowledge about new topics in various scientific fields- from astronomy, to medicine, to cognitive science and psychology- we have it all! Issues are published at the end of each month, but even if writing doesn’t interest you, we will always welcome artists and web designers to help us with our online work and website. Be part of our tight-knit community, and come join us on Tuesdays in Rm. 105!"),
    Club(name:"Tino Poetry Club", email: "tinopoetryclub@gmail.com", description: "No Description."),
    Club(name:"Tino Photography Club", email: "photographyclub.tino@gmail.com", description: "Photography Club provides Tino with photos from school events and more while also spreading the love for photography. Members learn and practice taking photos at every situation, ranging from school events to scenic locations."),
    Club(name:"Tino Music Club", email: "tinomusicclub@gmail.com", description: "YMusic club is a place where anyone can come and enjoy music, whether you’ve been playing an instrument for years, want to learn, or make your own music. We provide an opportunity for people to collaborate with other musicians their age, as well as chances to perform. After all, music isn’t meant to be hidden away, but shared with everyone! Because of this, music club’s goal is to make music available to as many people as possible."),
    Club(name:"Tino Magic Society", email: "tinomagicsociety@gmail.com", description: "Tino Magic Society is a club where anyone with a passion for magic can come and learn. At every meeting, we will be showcasing 1-2 tricks and explaining the logic or sleight-of-hand behind it. There will also be time for members to show-off any tricks they’ve learned by themselves. This year, we will be teaching many different types of magic such as rope, card, and coin tricks."),
    Club(name:"Tino Chess Club", email: "tinochessclub@gmail.com", description: "The Cupertino Chess Club focuses on playing and teaching chess. We host and attend chess tournaments amongst various other school chess teams. We practice chess by meeting every week to play against other players of our level. We also learn chess through solving puzzles or going over our games every week with the help of high leveled players. This practice helps us for our tournaments and we were able to achieve third place last year. We also came second place in another tournament between all FUHSD schools. We aim to come first place in both tournaments this year."),
    Club(name:"Tino Artists", email: "tinoartclub@gmail.com", description: "Tino Artists’ Club is a creative environment open to all students at Cupertino. We believe that art is a way to reflect culture, beliefs, and promote individuality. Therefore, our club offers workshops, projects, and opportunities to refine motor skills."),
    Club(name:"Stagecraft", email: "catstagemanagement@gmail.com", description: "We are the technical theatre branch of C.A.T, the CHS Drama Department! With many different departments including lights, sound, costumes, and props, there’s something for everyone. Come join and form lifelong friendships in a team-forward, dynamic setting!"),
    Club(name:"Quizbowl", email: "tinoquizbowl@gmail.com", description: "Tino Quizbowl is a student organization that is an offshoot of the national organization: National Academic Quiz Tournament, which is dedicated to hosting and holding state and national level trivia competitions. Our club allows students to strengthen their academic abilities in and out of the classroom in a variety of subjects including, but not limited to: literature (novels, short stories, drama, poetry), science (biology, chemistry, physics, astronomy, mathematics, computer science, earth science, laboratory science), history (American, British, European, world), fine arts (painting, music, opera, jazz, ballet, photography, sculpture, architecture, film), religion, mythology, and philosophy, social sciences (psychology, economics, anthropology/sociology, linguistics), geography (cities, states/provinces/regions, natural landmarks), current events, and pop culture."),
    Club(name:"Psychology Club", email: "tinopsychology@gmail.com", description: "Tino Psychology Club is a place where we hope to raise awareness of the mental health issues that frequent CHS, and our society in general. With a wide range of fun and engaging activities, we hope to cultivate an interest in the field of psychology as well as provide a welcoming environment for students to unwind."),
    Club(name:"History Club", email: "tinohistory@gmail.com", description: "We’re here to make history much more fun than it has ever been. Our goal is to make history come alive through powerful movies, documentaries and books that will leave you with a deeper understanding and love for history. History can be made fun and exciting if you know the right way to do it, and we do! So come join us to have fun while learning important stuff! We will also be hosting History bowl events that are schoolwide. There is something for everyone in this club; we look forward to seeing you!"),
    Club(name:"Go Club", email: "cupertinogoclub@gmail.com", description: "Go is an ancient board game which takes simple elements: line and circle, black and white, stone and wood, combines them with simple rules and generates subtleties which have enthralled players for millennia. As a go club, we aim to promote this game throughout the school and share this wonderful game with others."),
    Club(name:"Filmmaking", email: "tinofilmmaking@gmail.com", description: "Tino Filmmaking Club is an organization dedicated to teach new or experienced people all aspects of filmmaking through lessons, performing what is learned, and entering in competitions. We welcome all people of all different levels of experience (professional or a hobbyist) where there is always something to learn for anyone."),
    Club(name:"Cupertino Gaming Club", email: "gamingclub.tino@gmail.com", description: "Cupertino Gaming Club invites all students to hang out and enjoy playing video games together, in a stigma-free environment! It doesn’t what, how, or why you play, as long as you share the same passion for gaming that we do!"),
    Club(name:"Cooking Club", email: "cupertinocooking@gmail.com", description: "    Our goal is to teach people to be able to create and make their own food for their daily life."),
    Club(name:"Comedy Hour", email: "comedyhourcaptains@gmail.com", description: "Comedy Hour aims to practice and perform comedy improvisation for entertainment. Members will participate in shows four times a year, and attend practice sessions throughout the year. All students, parents, and teachers are welcome to watch shows and join the experience of live comedy improv with audience participation."),
    Club(name:"Bullet Journal and Calligraphy Club", email: "tinobulletjournalclub@gmail.com", description: "Cupertino Bullet Journal Club creates a strong community of people who are passionate about bullet journaling and expressing their creativity. A bullet journal is a combination between a planner, a to do list and a journal. It allows users to express their creativity while being organized. Our club will teach members how to start and sustain a journal, as well as how to do calligraphy, watercolor and more! Throughout the year we will also be doing different workshops such as sticker making, scrapbooking and card making. We provide all the supplies and no previous knowledge is needed to join."),
    Club(name:"ASL (American Sign Language) Club", email: "cupertinoasl@gmail.com", description: "This club is to provide the students at Tino a space to learn more about American Sign Language and Deaf/Hard of Hearing culture. We aim to educate the student population through interactive lessons and discussions about sign language and current issues related to the Deaf/HoH community. Activities will involve active participation."),
    Club(name:"Animanga Club", email: "animanga1415@gmail.com", description: "A place where you can watch anime, hangout with friends, and meet new people."),
    Club(name:"TinoSpike", email: "tinospike.club@gmail.com", description: "Do you enjoy playing volleyball? Are you looking for some pre-season prep or just to have fun? Come to Tino Spike! We are a volleyball club who meet during lunch for open gyms and to meet new people who share the same passion. We also host an annual volleyball tournament, where any skill levels are welcome to form their own team and participate for prizes."),
    Club(name:"Tino Sports Med", email: "tinosportsmed@gmail.com", description: "Tino Sports med will mainly focus on informing students about sports related injuries. We will inform the students on how to prevent these injuries, as well as how to treat them. Our club will work hard to get students hands on experience with the trainer at school, and we will also help them get volunteering hours outside of school."),
    Club(name:"Tino Hiphop", email: "cupertinohiphop@gmail.com", description: "No Description."),
    Club(name:"Tino Futsal", email: "nevillepv@gmail.com", description: "Futsal club opens the field house, allowing anyone interested to come and play indoor soccer. By improving their soccer skills, members improve their chances of making it onto the school soccer team. Members also have the chance to meet and create friendships with others who have a passion for soccer. Almost all meetings are entirely dedicated to giving members the full lunch period to play futsal."),
    Club(name:"Tino Bike Club", email: "cupertinohighbikeclub@gmail.com", description: "Our club is a community of cyclists that enjoy going on any ride from a coffee ride to an overnight camping trip. We love to explore the natural scenery around the south bay and along the way we enjoy some of the best food. We also teach other cyclists about road safety and etiquette as a way of giving back to the community and making sure everyone is safe."),
    Club(name:"Tino Badminton Club", email: "chs.baddy@gmail.com", description: "The Badminton Club strives to offer a place for new and experienced badminton player to learn the sport, hone their skills, and compete in a friendly and inclusive environment."),
    Club(name:"Women's Empowerment Association", email: "cupertinowea@gmail.com", description: "The Women’s Empowerment Association aims to empower women to advocate for themselves through a variety of means, such as advocacy workshops, global education, guest speaker events, and open discussion. We strive to create change at Tino and beyond by promoting gender equality and a safer campus community. All genders are welcome at WEA!"),
    Club(name:"Tino Humane Society Club", email: "tinohumanesocietyclub@gmail.com", description: "Tino Humane Society emphasizes the importance of animal rights. The club shows a variety of animal related issues through powerpoint presentations, youtube videos, and documentaries. We introduce our members to first hand experience with animals by immersing them in volunteer work (like Paws on Main, Corgi Con), visits to animal facilities, and animal incorporated social events."),
    Club(name:"Tino Cancer Society (TCS)", email: "tinocancersociety2020@gmail.com", description: "Cancer is something that people do not like to talk about as it affects the lives of so many people. However, because of this fact, it is crucial that we do bring attention to this. In TCS, we will spread awareness of different types of cancer and what symptoms to look for. We will also be talking about the cancer research being done so far and possible cures that have been presented. Additionally, we will be having guest speakers and volunteering opportunities that will give students a chance to empathize and join the cause to fight cancer!"),
    Club(name:"Tino Best Buddies", email: "cupertinobestbuddies@gmail.com", description: "Tino Best Buddies is just one chapter of a worldwide organization that is working on ending discrimination that our peers with Intellectual or Developmental Disabilities (or IDDs) face. Our club helps promote this cause by pairing members into one-to-one friendships and by actively including all our members during our weekly lunch meetings, where we play basketball, solve puzzles, and just hang out. We also meet up outside of school for potlucks, bowling, movies, and more! Finally, every year in San Francisco, we raise awareness for the cause of inclusion during our Friendship Walk, which is filled with fun!"),
    Club(name:"Gender Sexuality Alliance", email: "cupertinohs.gsa@gmail.com", description: "We are a club that seeks to spread awareness about the LGBTQ+ community and seeks to provide a safe environment for those that need it. We shall attempt to hold a social for every major holiday and watch a movie, enjoy free food, and/or play a board game. We plan to invite speakers to talk about their past experiences in a Q&A panel."),
    Club(name:"Environmental Club", email: "cupertinoenvironmentalclub@gmail.com", description: "The Cupertino Environmental Club seeks to make our community more environmentally sustainable and informed. We pioneer projects on campus to help reduce waste, and attend environmental events in the community. We have also created the Cupertino Youth Climate Action Team, mentored by City Council Aide Tara Sreekrishnan, and Stanford taught physicist/political activist Gary Latshaw. Our team members have successfully lobbied the Cupertino City Council to add initiatives to their 2019 City Council Work Program, and are in the process of numerous on campus projects with the district. Overall, our goal is to help create a new generation of environmentally conscious leaders."),
    Club(name: "California Scholarship Federation (CSF)", email: "info.tinocsf@gmail.com", description: "CSF is an honor society that strives to connect its members to diverse volunteering opportunities. It rewards its members for both their academic achievements and dedication to community service, offering eligible seniors the chance to apply for a $500 scholarship. As a club, we strive to provide exciting community service opportunities and are open to all grade levels."),
    Club(name: "French Honor Society", email: "lashfchs@gmail.com", description: "French Honor Society is an honor society dedicated to spreading Francophone cultures from around the globe and opportunities for students to learn and tutor in French. We host a lot of fun activities throughout the year where members can have fun while also learning about different cultures, from France, to Senegal, to Madagascar, to Quebec, and beyond. Throughout the year, we host movie nights, year-long house competitions, jeopardy games, and most of all, food days with crepes, cheese, and fondue!"),
    Club(name: "Japanese National Honors Society (JNHS)", email: "jnhs.chs@gmail.com", description: "Japanese National Honor Society is a national honor society that centers its events around Japanese culture. In addition to providing volunteering opportunities in the Japanese community, we also organize socials within our club to build a tight-knit family. We will aim to make the Japanese learning experience even more rewarding."),
    Club(name: "National Chinese Honor Society", email: "alexandriahunt4@gmail.com", description: "Aims to allow high-achieving students previously or currently enrolled in a Chinese course at Cupertino (Chinese 3, 4H, 5AP) earn recognition from the National Chinese Honor Society due their demonstration of citizenship, leadership, and communication, as well as their engagement in learning about Chinese culture and heritage through the club."),
    Club(name: "National Honor Society", email: "info.tinonhs@gmail.com", description: "Through granting credits for service at local partnered community service events, National Honor Society provides an avenue for high-achieving students to develop the values of the four pillars of NHS: scholarship, character, service, and leadership. Participation grants chapter members recognition from the central National Honor Society organization and senior members are eligible for cords at graduation."),
    Club(name: "National Math Honor Society", email: "tino.nmhs@gmail.com", description: "The National Math Honor Society is a club dedicated to enriching math-related experiences of students in the Cupertino High School community. With rewarding competitions, tutoring sessions, community outreach projects, and volunteering opportunities, NMHS is the perfect combination of applying mathematics in the real world, helping the community prosper, and developing an interest for math. In addition, NMHS is a registered chapter of the Mu Alpha Theta National Math Honor Society."),
    Club(name: "Spanish Honor Society", email: "cupertinoshh@gmail.com", description: "Spanish Honor Society aims to utilize our academic scholarship in Spanish to educate students in Spanish culture and language and provide them with exposure to Spanish in the real world through community service and competitions."),
    Club(name: "Global Health Club", email: "tino.globalhealthclub@gmail.com", description: "No Description"),
    Club(name: "Interact", email: "chsinteract12.5170@gmail.com", description: "Interact is a service organization that fosters leadership and responsible citizenship through both an international and community project, as well as various charity events, dinners, mixers, and service events."),
    Club(name: "Key Club", email: " cupertinohskeyclub@gmail.com", description: "Key Club is a service club that builds character and develops leadership. Through local volunteering events, we hope to encourage giving back to the community. All volunteering hours performed by members are tracked and recognized. Members are able to build character by meeting new people throughout service, social, and spirit events. Attending these events allow members to create long lasting relationships students from Cupertino, as well as Key Club members locally. Workshops are provided throughout the year that communicate insightful leadership advice that is useful for personal life. Key Club is a community service club that promotes four core values: leadership, character building, caring, and inclusiveness."),
    Club(name: "LEO", email: "chsleoclub.info@gmail.com", description: "The purpose of LEO Club is to provide community service opportunities for students in CHS. LEO Club strives to take volunteer service to a more personal level. Through volunteering events, LEO Club focuses on connecting students to their community to allow them to directly help solve problems that our community is facing. Our projects and work affect our local community directly, rather than indirectly."),
    Club(name: "Red Cross Club", email: "cupertinoredcross@gmail.com", description: "Our club educates its members about the different ways that the Red Cross organization helps the world during a crisis. It gives community service hours for students who put their time into helping other people. Activities which the club conducts, are installing fire alarms in houses, conducting blood drives, and hosting CPR trainings."),
    Club(name: "Tino Octagon", email: "tinooctagon@gmail.com", description: "Tino Octagon is part of Junior Optimist Octagon International (JOOI) and we strive to provide opportunities for students to demonstrate and improve their leadership abilities and participate in a variety of community service events that involve teamwork, interactions, and positive work ethics. Members/Students who earn 25 hours or more by the end of the school year will be eligible for annual President’s Volunteer Service Award."),
    Club(name: "UNICEF", email: "tinounicef@gmail.com", description: "We are a humanitarian club that aims to spread awareness about the goals of the larger organization UNICEF and the international causes they work to alleviate. We organize fundraisers throughout the year in order to collect donations for UNICEF. We also offer a variety of opportunities, including membership in committees, outreach and volunteer events, taking part in fundraisers, and more."),
    Club(name: "Aviation and Rocketry", email: "Steemers", description: "The purpose of this club is to provide exposure to rocketry and other facets of aeronautical engineering to students of all skill groups. The club will focus on a more balanced theme, educating club members of the basics of Aviation/Rocketry while having fun. Club members will be making gliders, model rockets, experimenting with plane wings, flying drones, learning the physics behind each test/experiment we conduct, and much more. If enough interest is gained, we plan to introduce a competition side of the club."),
    Club(name: "Cupertino Engineering", email: "cupertinoengineering@gmail.com", description: "We aim to provide students with exposure to the field of engineering through various activities and provide a pathway to the national TSA Teams competition to solve real world problems."),
    Club(name: "Cupertino Science Society", email: "tino.sciencesociety@gmail.com", description: "Cupertino Science Society is an organization dedicated to the promotion of scientific education throughout the community. We strive to foster student interest in areas of scientific research and prepare them for competitive events such as Science Bowls and Olympiads. The club also connects members to volunteering organizations and internships to allow member to gain leadership experience and practice science in the real world."),
    Club(name: "Game Development Club", email: "cupertinogamedev@gmail.com", description: "The Cupertino Game Development Club is a group of people dedicated to making games. We meet weekly to explore the variety of skills necessary for game development and put those skills into practice by working on small game projects of our own. We share our creations, ideas, and knowledge to educate and entertain each other."),
    Club(name: "Girls Who Code", email: "McLeod", description: "No Description"),
    Club(name: "Robotics", email: "cupertinorobotics@gmail.com", description: "No Description"),
    Club(name: "Tino Math Club", email: "tinocompetitivemath@gmail.com", description: "Tino Math Club explores aspects of math not typically emphasized in high school. We also prepare for and participate in math competitions such as the AMC 10/12 and the Stanford Math Tournament. Meetings feature presentations and problems on topics such as cryptography, geometry in more than three dimensions, and modular arithmetic.Through Math Club, members will learn problem solving and logical thinking skills, and develop an appreciation for the beauty of math."),
    Club(name: "Tino STEM", email: "tinoscienceclub@gmail.com", description: "Tino STEM is a club oriented toward those who are interested in science, technology, engineering, or math- we do demos, guest speaker events, tours, and competitions in the STEM area and offer both mentorship and companionship to any students interested in STEM."),
    Club(name: "Tino Student Doctors", email: " tinostudentdoctors@gmail.com", description: "Student Doctors Club is a group of students who are interested in the medical field or want to get to know more about the medical field. We will have guest speakers, fun games, and simulations. The guest speakers will be able to tell the members about how they got into the medical field, their education experience, and what they do in their day to day life. The members will get hands-on experience with the field because of the kits and workshops we will provide."),
    Club(name: "Tinotronics (Electronics)", email: "tinotronics18@gmail.com", description: "This club will present numerous opportunities for high schoolers to gain hands-on experience with circuitry and learn the underlying concepts of how and why different types of electronic circuits work. This in turn will help students further the exploration, interest, and innovation of Electrical Engineering. Our club will also help students to make simple gadgets that will both teach them concepts in engineering and benefit them in their daily lives."),
    Club(name: "Tinovation", email: "tinovationofficerteam@gmail.com", description: "Tinovation is Cupertino High School’s student-run computer programming and hackathon club. Like-minded students come together in a cultivating learning environment to develop products using industry-standard programming languages such as HTML, CSS, Javascript, Java, Swift, Python and more, attend tutoring sessions for Computer Science classes as well as personal projects, and compete in various hackathons. Hackathons are essentially programming competitions, and members will receive extensive opportunities to form teams and compete in such events. In summary, Tinovation provides a unique learning environment for those wishing to develop an interest in or explore the vast world of computer programming and hackathons!"),
    Club(name: "Women in Tech", email: "chswomenintech@gmail.com", description: "The goal of Women In Tech is to encourage and raise awareness about the variety of tech related opportunities for women in the world. We also aim to create a safe environment where girls can learn several topics and ask questions. We believe that once girls at our school are exposed to the wide variety of tech related opportunities we offer, they will become more inclined to have a tech related job in the future. We host several guest speaker events, a women in tech panel, provide volunteer opportunities, and teach a variety of computer science topics through workshops."),
    Club(name: "Future Business Leaders of America (FBLA)", email: "tino.fbla@gmail.com", description: "Offers opportunities to compete nationally, participate in chapter projects, volunteer, go on business tours, and learn from guest speakers of world-renowned companies."),
    Club(name: "Mock Trial", email: "cupertinomocktrial@gmail.com", description: "Cupertino Mock Trial is the only law-based club on-campus, aimed at offering students the opportunity to prepare, practice, and compete in courtroom competitions. Over the course of the year, students prepare and present both a prosecution and defense case based on a fictional fact situation. The club emphasizes skills such as public speaking, critical thinking, and comprehension of legal concepts."),
    Club(name: "Model United Nations", email: "tino.unitednations@gmail.com", description: "Encourages discussion on global issues through MUN conferences, community service, and campaigns of advocacy."),
    Club(name: "Speech and Debate", email: "cupertinospeechanddebate@gmail.com", description: "As one of the largest clubs on campus, Speech and Debate is committed to teaching students the skills of public speaking, communication and confidence, and providing opportunities to compete on the local, state, and national level. Previously, Tino SD members have been ranked among the top in the nation, and have won awards at prestigious tournaments."),
    Club(name: "Tino Investors", email: "tinoinvestors@gmail.com", description: "Tino Investor teaches students how to invest in the stock market. Our meetings are every Tuesday in Mrs. Schaetzke’s room, 915. We use presentations, stock simulations, and games to help teach the different aspects of investing. Come check us out to learn more on investing or to make new friends."),
    Club(name: "Chinese Culture Club", email: "cupertinohschinesecultureclub@gmail.com", description: "Chinese Culture Club is a club where individuals come together to establish the thriving of chinese culture within us. We celebrate Chinese festivals and participate in activities in relation to the lives of Chinese people. These include hosting a Chinese New Year potluck, and playing mahjong or chess. We are bounded by enthusiasm and the feeling of togetherness."),
    Club(name: "Footprints Christian Club", email: "chsfcc@gmail.com", description: "Footprints Christian Club is an environment in which people of any background can come together to learn about Christianity and grow in their faith. We host Bible studies, fellowship gatherings, prayer meetings, worship, and special speakers. Our desire is to show our campus the true spirit of Christianity and spread Christ’s love."),
    Club(name: "International Club", email: "internationalclubofficers@gmail.com", description: "We are a student organization that strives to bring all students together through fun and constructive events. The club provides students with the opportunities for cultural exchange and a chance to learn more about the world."),
    Club(name: "JTASA", email: "cupertinojtasa@gmail.com", description: "JTASA (Junior Taiwanese American Student Association) exists to unify, connect, and strengthen the Taiwanese-American community by providing volunteering and networking opportunities. JTASA’s goal is to spread awareness of Taiwanese culture on campus as well as helping students identify with their Taiwanese heritage. JTASA is a branch of the nonprofit Taiwanese American Citizens League (TACL), whose mission is to improve the quality of life of Taiwanese Americans in the United States. You do not have to be Taiwanese to join!"),
    Club(name: "KASA", email: "tinokasa@gmail.com", description: "Korean-American Student Association (KASA) aims to promote Korean culture through both Kpop dance performances and various club events. KASA performs at school rallies as well as public events, and we’ve held dance workshops and performances with other high school and college dance teams. We also spread awareness of Korean culture on campus through activities such as games, arts and crafts, fundraisers, inter-district socials, etc. KASA is open to all ethnicities."),
    Club(name: "Muslim Student Association", email: "ayabz.2002@gmail.com", description: "This club provides a safe place for muslim cupertino students as well as a place to pray Friday Jummah. There will be a Jummah every friday along with a small discussion. Each year the club hosts World Hijab Day for students to learn more about the hijab as well as muslims in general, and students will also have the opportunity to ask us questions."),
    Club(name: "Tino ICAA", email: "tinoicaa@gmail.com", description: "Tino ICAA is a culturally affiliated club offering Cupertino High School students the opportunity to participate in a variety of activities. We offer community service events through an organization called India Literacy Project, and have a competitive dance team, Tino Dhadkan, that performs at cultural shows in the community and hosts its own cultural show during the second semester. Tino ICAA celebrates cultural and ethnic diversity and welcomes all to join."),
    ]
    override func viewDidLoad() {
        super.viewDidLoad()
        interestField.delegate = self
        // Do any additional setup after loading the view.
    }

    @IBAction func enterTapped(_ sender: Any) {
        textView.text = ""
        var interest = interestField.text!
        var clubInterests: [Club] = []
        for club in cupertinoClubs{
        if(club.description.containsIgnoringCase(find: interest) || club.name.containsIgnoringCase(find: interest)){
            clubInterests.append(club)
            }
        }
        
        if (clubInterests.count == 0) {
            textView.text = "No Results Found"
        }
        
        else {
            clubInterests = clubInterests.sorted(by: {$0.name < $1.name})
            for club in clubInterests {
                textView.text += "Club: \(club.name)\nContact Info: \(club.email)\nDescription: \(club.description)\n\n"
            }
        }
        
        textView.isScrollEnabled = true
        textView.isUserInteractionEnabled = true
        textView.showsVerticalScrollIndicator = true
        textView.showsHorizontalScrollIndicator = true
        textView.translatesAutoresizingMaskIntoConstraints = false
    }
}

extension ViewControllerCupertino : UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
}

